name: Build Windows Forms App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      MSBUILDDISABLENODEREUSE: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clean workspace
      run: |
        Remove-Item -Recurse -Force Compilador/obj, Compilador/bin -ErrorAction SilentlyContinue

    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          Microsoft.WindowsDesktop.App.Ref

    - name: Install required workloads
      run: dotnet workload install windowsdesktop --skip-manifest-update

    - name: Restore dependencies
      run: dotnet restore Compilador.sln --verbosity detailed

    - name: Build with resource workaround
      shell: powershell
      run: |
        $env:UseSharedCompilation = "false"
        dotnet build Compilador.sln `
          -c Release `
          --no-restore `
          /p:GenerateResourceUsePreserializedResources=true `
          /p:BuildInParallel=false `
          /p:UseTaskHost=false `
          /nr:false

    - name: Publish application
      run: |
        dotnet publish Compilador/Compilador.csproj `
          -c Release `
          -r win-x64 `
          --self-contained false `
          --no-build `
          /p:PublishSingleFile=true `
          /p:IncludeNativeLibrariesForSelfExtract=true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CompiledApp
        path: |
          Compilador/bin/Release/net8.0-windows/publish/*
          Compilador/bin/Release/net8.0-windows/*.exe
