name: .NET Windows Forms Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]  # Você pode adicionar Debug também se necessário

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Compilador.sln

    - name: Fix MSBuild Path (Importante para o erro GenerateResource)
      run: |
        # Corrige problemas com o MSBuild e recursos
        echo "Adding MSBuild to PATH"
        echo "$env:GITHUB_WORKSPACE\Microsoft.NET.Sdk\tools" >> $env:GITHUB_PATH
        echo "$env:ProgramFiles\dotnet\sdk\$(dotnet --version)\MSBuild\Current\Bin" >> $env:GITHUB_PATH

    - name: Build Solution
      run: |
        # Build com verificação de recursos
        dotnet build Compilador.sln --configuration ${{ matrix.configuration }} --no-restore /p:GenerateResourceUsePreserializedResources=true
        
    - name: Publish Application
      run: |
        dotnet publish Compilador\Compilador.csproj \
          -c ${{ matrix.configuration }} \
          -r win-x64 \
          --self-contained false \
          /p:GenerateResourceUsePreserializedResources=true \
          /p:ErrorOnDuplicatePublishOutputFiles=false

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Application-${{ matrix.configuration }}
        path: Compilador\bin\${{ matrix.configuration }}\net8.0-windows\publish\
