name: .NET Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Compilador.sln

    - name: Build
      run: dotnet build Compilador.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Test (if tests exist)
      run: dotnet test
      if: contains(matrix.configuration, 'Release')  # Só roda testes em Release

    - name: Publish as single file (opcional)
      run: dotnet publish Compilador\Compilador.csproj -c ${{ matrix.configuration }} -r win-x64 --self-contained false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Binaries-${{ matrix.configuration }}
        path: |
          Compilador\bin\${{ matrix.configuration }}\**
          Compilador\obj\${{ matrix.configuration }}\**
