name: .NET Windows Forms Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Compilador.sln

    - name: Install Windows Desktop SDK
      run: dotnet workload install windowsdesktop

    - name: Build Solution (Workaround for GenerateResource)
      shell: cmd
      run: |
        set MSBUILDDISABLENODEREUSE=1
        dotnet build Compilador.sln -c %configuration% ^
          /p:GenerateResourceUsePreserializedResources=true ^
          /p:UseSharedCompilation=false ^
          /p:BuildInParallel=false ^
          /nr:false

    - name: Publish Application
      run: |
        dotnet publish Compilador\Compilador.csproj \
          -c ${{ matrix.configuration }} \
          -r win-x64 \
          --self-contained false \
          /p:GenerateResourceUsePreserializedResources=true \
          /p:ErrorOnDuplicatePublishOutputFiles=false

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Application-${{ matrix.configuration }}
        path: Compilador\bin\${{ matrix.configuration }}\net8.0-windows\publish\
